name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    
      - 'prototype/**'    

permissions:
  packages: write

jobs:

  build:
    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}\package'
      testProject: '${{ github.workspace }}\Container\tests\Unit\Unity.Container.Tests.csproj'

    steps:
    - name: Checkout Container
      uses: actions/checkout@v3
      with:
        path: Container
        fetch-depth: 0

    - name: GitVersion
      run: | 
        choco install gitversion.portable -pre -y --no-progress
        gitversion /l console /output buildserver /config .github\gitversion.yml /targetpath Container

    # - name: Setup .NET Core SDK
    #   uses: actions/setup-dotnet@v3.0.3
    #   with:
    #     dotnet-version: '8.0'
        
    - name: Build
      run: | 
        dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ github.workspace }}\Container\src\Unity.Container.csproj
    #    dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ env.testProject }}

    # - name: Test
    #   run: | 
    #     dotnet test ${{ env.testProject }}

    - name: Publish Local Package
      run: |
        dotnet nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github

    - name: Label Fixed Issues
      uses: gh-bot/fix-labeler@master        
      with:
        path: Container
